import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, Search, Trash2 } from 'lucide-react'
import toast from 'react-hot-toast'
import api from '../../api/axios.js'
import AdminLayout from '../../components/admin/AdminLayout.jsx'

const statuses = ['pending', 'approved', 'rejected']

function ManageReviews() {
  const [data, setData] = useState({ reviews: [], total: 0, hasMore: false })
  const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [rating, setRating] = useState(''); const [page, setPage] = useState(1); const [reviewToDelete, setReviewToDelete] = useState(null); const [deleting, setDeleting] = useState(false)
  const loadReviews = useCallback(async (nextPage = 1) => {
    setLoading(true)
    try { const res = await api.get('/reviews', { params: { page: nextPage, search, status, rating } }); setData(res.data); setPage(nextPage) } catch { toast.error('Failed to load reviews') } finally { setLoading(false) }
  }, [rating, search, status])
  useEffect(() => { const timer = setTimeout(() => loadReviews(), 250); return () => clearTimeout(timer) }, [loadReviews])
  const updateStatus = async (id, nextStatus) => { try { await api.put(`/reviews/${id}/status`, { status: nextStatus }); toast.success('Review status updated'); loadReviews(page) } catch (err) { toast.error(err.response?.data?.message || 'Unable to update review') } }
  const remove = async () => { if (!reviewToDelete) return; setDeleting(true); try { await api.delete(`/reviews/${reviewToDelete._id}`); toast.success('Review deleted'); setReviewToDelete(null); loadReviews(data.reviews.length === 1 && page > 1 ? page - 1 : page) } catch (err) { toast.error(err.response?.data?.message || 'Unable to delete review') } finally { setDeleting(false) } }
  return <AdminLayout title="Reviews & Ratings" subtitle={`${data.total} review${data.total === 1 ? '' : 's'} · ${data.reviews.filter((review) => review.status === 'pending').length} pending on this page`}>
    <div className="mb-5 grid gap-3 md:grid-cols-[1fr_180px_150px]"><label className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search product or review" className="w-full rounded-lg border border-gray-300 py-2.5 pl-10 pr-3 text-sm" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm"><option value="">All statuses</option>{statuses.map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select><select value={rating} onChange={(event) => setRating(event.target.value)} className="rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm"><option value="">All ratings</option>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} stars</option>)}</select></div>
    {loading ? <p className="text-gray-500">Loading reviews…</p> : data.reviews.length === 0 ? <p className="rounded-xl bg-white p-6 text-gray-500">No reviews match these filters.</p> : <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-4">Product</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Rating</th><th className="px-5 py-4">Review</th><th className="px-5 py-4">Date</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{data.reviews.map((review) => <tr key={review._id}><td className="px-5 py-4 font-semibold text-gray-800">{review.product?.name || 'Deleted product'}</td><td className="px-5 py-4"><p>{review.user?.name || 'Unknown'}</p><p className="text-xs text-gray-400">{review.user?.email}</p></td><td className="px-5 py-4 text-brand-gold">{'★'.repeat(review.rating)}</td><td className="max-w-sm px-5 py-4"><p className="font-medium text-gray-800">{review.title}</p><p className="mt-1 text-gray-600">{review.comment}</p></td><td className="px-5 py-4 text-xs text-gray-500">{new Date(review.createdAt).toLocaleDateString('en-MY')}</td><td className="px-5 py-4"><select value={review.status} onChange={(event) => updateStatus(review._id, event.target.value)} className="rounded-full bg-gray-100 px-3 py-1.5 text-xs font-semibold">{statuses.map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select></td><td className="px-5 py-4"><button onClick={() => setReviewToDelete(review)} className="rounded p-2 text-rose-600 hover:bg-rose-50" aria-label="Delete review"><Trash2 size={17} /></button></td></tr>)}</tbody></table></div>}
    {(page > 1 || data.hasMore) && <div className="mt-5 flex gap-3"><button disabled={page === 1} onClick={() => loadReviews(page - 1)} className="rounded-full border px-4 py-2 text-sm disabled:opacity-40">Previous</button>{data.hasMore && <button onClick={() => loadReviews(page + 1)} className="rounded-full bg-brand-blue px-4 py-2 text-sm font-semibold text-white">Next</button>}</div>}
    {reviewToDelete && <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-review-title"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><AlertTriangle className="mb-4 text-rose-600" size={28} /><h2 id="delete-review-title" className="text-lg font-bold text-gray-900">Delete this review?</h2><p className="mt-2 text-sm leading-6 text-gray-600">This will permanently remove {reviewToDelete.user?.name || 'this customer'}’s review for {reviewToDelete.product?.name || 'this product'}. This action cannot be undone.</p><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={deleting} onClick={() => setReviewToDelete(null)} className="rounded-full border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Cancel</button><button type="button" disabled={deleting} onClick={remove} className="rounded-full bg-rose-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{deleting ? 'Deleting…' : 'Delete review'}</button></div></div></div>}
  </AdminLayout>
}
export default ManageReviews
